### PR TITLE
Feature/app

### PR DESCRIPTION
**Pull request by george-shammar**
This Pull Request seeks to merge the following features to the develop branch:
- A button for the user to add a new book.
- A delete button.
- A button to update the read status.

### CODE REVIEW

**Review by rindrajosia — CHANGES_REQUESTED** [review]
Friendly reminder: You should make sure that your repo looks professional before review.
Please take a step back and read a lesson here https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/.
Then apply 3 simple rules from this lesson (it will be easy as you can use a template provided there).
This Code Review Request will be marked as **invalid** in your Dashboard, so please submit a new one once you are ready!

**Review by rindrajosia — CHANGES_REQUESTED** [review]
Changes Required :red_circle:
To Highlight: :angel:

- User can add book :+1: 
- User can see list of books :100: 
- User can change the Book read status :+1: 

To Improve :factory_worker: (REQUIRED):

- [ ] Good readme file, all information is there but I suggest you use tools like grammarly that will help you in your grammar.
- [ ] Make sure that the screenshot in your readme file corresponds with your APP.
- [ ] For UX, it will be nice if you add a Label for each input text because the user doesn't know in which input text he must enter the book title, book author, ...
- [ ] When I click on Delete button, it always deletes the first one in the array:


Nice to have:

- the form used to create a book should have validations, you should not be able to create an empty book
-  It has data persistence by saving, retrieving, and updating the library books using the [localstorage API.](https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API) ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/library/localstorage_stretch_requirement.png) from [Odin Project](https://www.theodinproject.com/courses/javascript/lessons/library))

That's it, you can submit another code review request after making these changes :recycle: :innocent:
With all my respect :pray:
Rindra Josia

**Review by uche-inyama — CHANGES_REQUESTED** [review]
## Changes Required

### Hi @team :wave: 

Just a few updates to make.

* [x] While creating a book, irrespective of what I choose as the read status, the status comes out as **yes**.  Use the gif below as a reference:

* [ ] The screenshot you added to the readme is broken.



readStatus


#### That's it, fix these then submit another form for a code review.


### Have a great day :slightly_smiling_face: 

#### ``` Uchechukwu Henry Inyama ```

**Review by rindrajosia — APPROVED** [review]
Hello Team :wave:
Status: Project Approved :green_circle:

Bravo :clap: :clap:

REQUIRED: Add info in the Acknowledgments section

With all my respect :pray:

**Pull request merged**
